#!/bin/tcsh -xef

echo "auto-generated by afni_proc.py, Fri Jan 22 11:42:45 2016"
echo "(version 4.57, December 7, 2015)"
echo "execution started: `date`"

# execute via : 
#   tcsh -xef proc.sub001_run1 |& tee output.proc.sub001_run1

# =========================== auto block: setup ============================
# script setup

# take note of the AFNI version
afni -ver

# check that the current AFNI version is recent enough
afni_history -check_date 28 Oct 2015
if ( $status ) then
    echo "** this script requires newer AFNI binaries (than 28 Oct 2015)"
    echo "   (consider: @update.afni.binaries -defaults)"
    exit
endif

# the user may specify a single subject to run with
if ( $#argv > 0 ) then
    set subj = $argv[1]
else
    set subj = sub001_run1
endif

# assign output directory name
set output_dir = $subj.results

# verify that the results directory does not yet exist
if ( -d $output_dir ) then
    echo output dir "$subj.results" already exists
    exit
endif

# set list of runs
set runs = (`count -digits 2 1 1`)

# create results and stimuli directories
mkdir $output_dir
mkdir $output_dir/stimuli

# copy stim files into stimulus directory
cp                                                                                                                                                                 \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond001_onset_times.txt \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond002_onset_times.txt \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond003_onset_times.txt \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond004_onset_times.txt \
    $output_dir/stimuli

# copy anatomy to results dir
3dcopy                                                                                                \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/anatomy/mprage_defaced.nii \
    $output_dir/mprage_defaced

# ============================ auto block: tcat ============================
# apply 3dTcat to copy input dsets to results dir, while
# removing the first 0 TRs
3dTcat -prefix $output_dir/pb00.$subj.r01.tcat \
    /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/BOLD/task001_run001/bold.nii'[0..$]'

# and make note of repetitions (TRs) per run
set tr_counts = ( 205 )

# -------------------------------------------------------
# enter the results directory (can begin processing data)
cd $output_dir


# ========================== auto block: outcount ==========================
# data check: compute outlier fraction for each volume
touch out.pre_ss_warn.txt
foreach run ( $runs )
    3dToutcount -automask -fraction -polort 3 -legendre                     \
                pb00.$subj.r$run.tcat+tlrc > outcount.r$run.1D

    # outliers at TR 0 might suggest pre-steady state TRs
    if ( `1deval -a outcount.r$run.1D"{0}" -expr "step(a-0.4)"` ) then
        echo "** TR #0 outliers: possible pre-steady state TRs in run $run" \
            >> out.pre_ss_warn.txt
    endif
end

# catenate outlier counts into a single time series
cat outcount.r*.1D > outcount_rall.1D

# ================================= tshift =================================
# time shift data so all slice timing is the same 
foreach run ( $runs )
    3dTshift -tzero 0 -quintic -prefix pb01.$subj.r$run.tshift \
             pb00.$subj.r$run.tcat+tlrc
end

# ================================= align ==================================
# a2e: align anatomy to EPI registration base
# (new anat will be aligned and stripped, mprage_defaced_al_keep+tlrc)
align_epi_anat.py -anat2epi -anat mprage_defaced+tlrc                        \
       -suffix _al_keep                                                      \
       -epi pb01.$subj.r01.tshift+tlrc -epi_base 0                           \
       -epi_strip 3dAutomask                                                 \
       -volreg off -tshift off

# -----------------------------------------
# warp anat follower datasets (affine)
3dAllineate -source mprage_defaced+tlrc                                      \
            -master mprage_defaced_al_keep+tlrc                              \
            -final wsinc5 -1Dmatrix_apply mprage_defaced_al_keep_mat.aff12.1D\
            -prefix anat_w_skull_warped

# ================================== blur ==================================
# blur each volume of each run
foreach run ( $runs )
    3dmerge -1blur_fwhm 4.0 -doall -prefix pb02.$subj.r$run.blur \
            pb01.$subj.r$run.tshift+tlrc
end

# ================================== mask ==================================
# create 'full_mask' dataset (union mask)
foreach run ( $runs )
    3dAutomask -dilate 1 -prefix rm.mask_r$run pb02.$subj.r$run.blur+tlrc
end

# create union of inputs, output type is byte
3dmask_tool -inputs rm.mask_r*+tlrc.HEAD -union -prefix full_mask.$subj

# ---- create subject anatomy mask, mask_anat.$subj+tlrc ----
#      (resampled from aligned anat)
3dresample -master full_mask.$subj+tlrc -input mprage_defaced_al_keep+tlrc \
           -prefix rm.resam.anat

# convert to binary anat mask; fill gaps and holes
3dmask_tool -dilate_input 5 -5 -fill_holes -input rm.resam.anat+tlrc       \
            -prefix mask_anat.$subj

# compute overlaps between anat and EPI masks
3dABoverlap -no_automask full_mask.$subj+tlrc mask_anat.$subj+tlrc         \
            |& tee out.mask_ae_overlap.txt

# note Dice coefficient of masks, as well
3ddot -dodice full_mask.$subj+tlrc mask_anat.$subj+tlrc                    \
      |& tee out.mask_ae_dice.txt

# ================================= scale ==================================
# scale each voxel time series to have a mean of 100
# (be sure no negatives creep in)
# (subject to a range of [0,200])
foreach run ( $runs )
    3dTstat -prefix rm.mean_r$run pb02.$subj.r$run.blur+tlrc
    3dcalc -a pb02.$subj.r$run.blur+tlrc -b rm.mean_r$run+tlrc \
           -expr 'min(200, a/b*100)*step(a)*step(b)'           \
           -prefix pb03.$subj.r$run.scale
end

# ================================ regress =================================
# ------------------------------
# run the regression analysis
3dDeconvolve -input pb03.$subj.r*.scale+tlrc.HEAD                        \
    -polort 3                                                            \
    -num_stimts 4                                                        \
    -stim_times 1 stimuli/cond001_onset_times.txt 'BLOCK(3.25,1)'        \
    -stim_label 1 mr_sw                                                  \
    -stim_times 2 stimuli/cond002_onset_times.txt 'BLOCK(3.25,1)'        \
    -stim_label 2 mr_ns                                                  \
    -stim_times 3 stimuli/cond003_onset_times.txt 'BLOCK(3.25,1)'        \
    -stim_label 3 pl_sw                                                  \
    -stim_times 4 stimuli/cond004_onset_times.txt 'BLOCK(3.25,1)'        \
    -stim_label 4 pl_ns                                                  \
    -gltsym 'SYM: mr_sw +mr_ns -pl_sw -pl_ns'                            \
    -glt_label 1 M-P                                                     \
    -gltsym 'SYM: mr_sw -mr_ns +pl_sw -pl_ns'                            \
    -glt_label 2 S-NS                                                    \
    -gltsym 'SYM: mr_sw -mr_ns'                                          \
    -glt_label 3 S-NS_M                                                  \
    -gltsym 'SYM: pl_sw -pl_ns'                                          \
    -glt_label 4 S-NS_P                                                  \
    -fout -tout -x1D X.xmat.1D -xjpeg X.jpg                              \
    -fitts fitts.$subj                                                   \
    -errts errts.${subj}                                                 \
    -bucket stats.$subj


# if 3dDeconvolve fails, terminate the script
if ( $status != 0 ) then
    echo '---------------------------------------'
    echo '** 3dDeconvolve error, failing...'
    echo '   (consider the file 3dDeconvolve.err)'
    exit
endif


# display any large pairwise correlations from the X-matrix
1d_tool.py -show_cormat_warnings -infile X.xmat.1D |& tee out.cormat_warn.txt

# create an all_runs dataset to match the fitts, errts, etc.
3dTcat -prefix all_runs.$subj pb03.$subj.r*.scale+tlrc.HEAD

# --------------------------------------------------
# create a temporal signal to noise ratio dataset 
#    signal: if 'scale' block, mean should be 100
#    noise : compute standard deviation of errts
3dTstat -mean -prefix rm.signal.all all_runs.$subj+tlrc
3dTstat -stdev -prefix rm.noise.all errts.${subj}+tlrc
3dcalc -a rm.signal.all+tlrc                                             \
       -b rm.noise.all+tlrc                                              \
       -c full_mask.$subj+tlrc                                           \
       -expr 'c*a/b' -prefix TSNR.$subj 

# ---------------------------------------------------
# compute and store GCOR (global correlation average)
# (sum of squares of global mean of unit errts)
3dTnorm -norm2 -prefix rm.errts.unit errts.${subj}+tlrc
3dmaskave -quiet -mask full_mask.$subj+tlrc rm.errts.unit+tlrc           \
          > gmean.errts.unit.1D
3dTstat -sos -prefix - gmean.errts.unit.1D\' > out.gcor.1D
echo "-- GCOR = `cat out.gcor.1D`"

# ---------------------------------------------------
# compute correlation volume
# (per voxel: average correlation across masked brain)
# (now just dot product with average unit time series)
3dcalc -a rm.errts.unit+tlrc -b gmean.errts.unit.1D -expr 'a*b' -prefix rm.DP
3dTstat -sum -prefix corr_brain rm.DP+tlrc

# create ideal files for fixed response stim types
1dcat X.xmat.1D'[4]' > ideal_mr_sw.1D
1dcat X.xmat.1D'[5]' > ideal_mr_ns.1D
1dcat X.xmat.1D'[6]' > ideal_pl_sw.1D
1dcat X.xmat.1D'[7]' > ideal_pl_ns.1D

# --------------------------------------------------------
# compute sum of non-baseline regressors from the X-matrix
# (use 1d_tool.py to get list of regressor colums)
set reg_cols = `1d_tool.py -infile X.xmat.1D -show_indices_interest`
3dTstat -sum -prefix sum_ideal.1D X.xmat.1D"[$reg_cols]"

# also, create a stimulus-only X-matrix, for easy review
1dcat X.xmat.1D"[$reg_cols]" > X.stim.xmat.1D

# ============================ blur estimation =============================
# compute blur estimates
touch blur_est.$subj.1D   # start with empty file

# -- estimate blur for each run in epits --
touch blur.epits.1D

# restrict to uncensored TRs, per run
foreach run ( $runs )
    set trs = `1d_tool.py -infile X.xmat.1D -show_trs_uncensored encoded \
                          -show_trs_run $run`
    if ( $trs == "" ) continue
    3dFWHMx -detrend -mask full_mask.$subj+tlrc                          \
        all_runs.$subj+tlrc"[$trs]" >> blur.epits.1D
end

# compute average blur and append
set blurs = ( `cat blur.epits.1D` )
echo average epits blurs: $blurs
echo "$blurs   # epits blur estimates" >> blur_est.$subj.1D

# -- estimate blur for each run in errts --
touch blur.errts.1D

# restrict to uncensored TRs, per run
foreach run ( $runs )
    set trs = `1d_tool.py -infile X.xmat.1D -show_trs_uncensored encoded \
                          -show_trs_run $run`
    if ( $trs == "" ) continue
    3dFWHMx -detrend -mask full_mask.$subj+tlrc                          \
        errts.${subj}+tlrc"[$trs]" >> blur.errts.1D
end

# compute average blur and append
set blurs = ( `cat blur.errts.1D` )
echo average errts blurs: $blurs
echo "$blurs   # errts blur estimates" >> blur_est.$subj.1D


# add 3dClustSim results as attributes to any stats dset
set fxyz = ( `tail -1 blur_est.$subj.1D` )
3dClustSim -both -mask full_mask.$subj+tlrc -fwhmxyz $fxyz[1-3]          \
           -prefix ClustSim
set cmd = ( `cat 3dClustSim.cmd` )
$cmd stats.$subj+tlrc


# ================== auto block: generate review scripts ===================

# generate a review script for the unprocessed EPI data
gen_epi_review.py -script @epi_review.$subj \
    -dsets pb00.$subj.r*.tcat+tlrc.HEAD

# generate scripts to review single subject results
# (try with defaults, but do not allow bad exit status)
gen_ss_review_scripts.py -exit0

# ========================== auto block: finalize ==========================

# remove temporary files
\rm -f rm.*

# if the basic subject review script is here, run it
# (want this to be the last text output)
if ( -e @ss_review_basic ) ./@ss_review_basic |& tee out.ss_review.$subj.txt

# return to parent directory
cd ..

echo "execution finished: `date`"




# ==========================================================================
# script generated by the command:
#
# afni_proc.py -subj_id sub001_run1 -script proc.sub001_run1 -scr_overwrite                                                                                          \
#     -blocks tshift align blur mask scale regress -copy_anat                                                                                                        \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/anatomy/mprage_defaced.nii                                                              \
#     -tcat_remove_first_trs 0 -dsets                                                                                                                                \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/BOLD/task001_run001/bold.nii                                                            \
#     -blur_size 4.0 -regress_stim_times                                                                                                                             \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond001_onset_times.txt \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond002_onset_times.txt \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond003_onset_times.txt \
#     /Users/u1591557/Documents/Single_Subject_Analysis/DS000006_data/sub001/model/model001/onsets/task001_run001/Stimulus_timing_files_AFNI/cond004_onset_times.txt \
#     -regress_stim_labels mr_sw mr_ns pl_sw pl_ns -regress_basis                                                                                                    \
#     'BLOCK(3.25,1)' -regress_opts_3dD -gltsym 'SYM: mr_sw +mr_ns -pl_sw                                                                                            \
#     -pl_ns' -glt_label 1 M-P -gltsym 'SYM: mr_sw -mr_ns +pl_sw -pl_ns'                                                                                             \
#     -glt_label 2 S-NS -gltsym 'SYM: mr_sw -mr_ns' -glt_label 3 S-NS_M                                                                                              \
#     -gltsym 'SYM: pl_sw -pl_ns' -glt_label 4 S-NS_P -regress_make_ideal_sum                                                                                        \
#     sum_ideal.1D -regress_est_blur_epits -regress_est_blur_errts
